name: sasank-jtml-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - albumentations=1.0.3=pyhd8ed1ab_0
  - alsa-lib=1.2.3=h516909a_0
  - aom=3.3.0=h27087fc_1
  - blas=2.111=openblas
  - blas-devel=3.9.0=11_linux64_openblas
  - blosc=1.21.0=h9c3ff4c_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py39hb9d737c_1004
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.0.4=h5f21a17_1
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2022.6.15=py39hf3d152e_0
  - cffi=1.15.1=py39he91dace_0
  - cfitsio=4.0.0=h9a35b8e_0
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - click=8.0.1=py39hf3d152e_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - cryptography=37.0.4=py39hd97740a_0
  - cudatoolkit=11.2.2=he111cf0_10
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py39h3811e60_1
  - dask-core=2022.2.1=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - dominate=2.7.0=pyhd8ed1ab_0
  - expat=2.4.7=h27087fc_0
  - ffmpeg=4.3.2=h37c90e5_3
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=h8e229c2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.30.0=py39hb9d737c_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2022.2.0=pyhd8ed1ab_0
  - geos=3.10.2=h9c3ff4c_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.70.2=h780b84a_4
  - glib-tools=2.70.2=h780b84a_4
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gputil=1.4.0=pyh9f0ad1d_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.5=hf529b03_3
  - gstreamer=1.18.5=h9f60fe5_3
  - harfbuzz=2.9.1=h83ec7ef_1
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.2=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2022.2.22=py39hf577088_0
  - imageio=2.16.1=pyhcf75d05_0
  - imgaug=0.4.0=pyhd8ed1ab_1
  - jasper=1.900.1=h07fcdf6_1006
  - jbig=2.1=h7f98852_2003
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - jxrlib=1.1=h7f98852_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libavif=0.9.3=h166bdaf_1
  - libblas=3.9.0=11_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=11_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.83.1=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libdrm=2.4.109=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=11.2.0=h69a702a_13
  - libgfortran5=11.2.0=h5c6108e_13
  - libglib=2.70.2=h174f98d_4
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.16=h516909a_0
  - libimagequant=2.17.0=h7f98852_1
  - liblapack=3.9.0=11_linux64_openblas
  - liblapacke=3.9.0=11_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libllvm13=13.0.1=hf817b99_2
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libopencv=4.5.0=py39_6
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libpq=13.5=hd57d9b9_1
  - libprotobuf=3.19.4=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_13
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.14.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=13.0.1=he0ac6c6_1
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.5.1=py39hf3d152e_0
  - matplotlib-base=3.5.1=py39h2fa2bec_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.29=haf5c9bc_1
  - mysql-libs=8.0.29=h28c427c_1
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
  - networkx=2.7.1=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.76=h2350873_0
  - numpy=1.21.2=py39hd8d4704_0
  - numpy-base=1.21.2=py39h2b8c604_0
  - nvtx=0.2.3=py39h3811e60_1
  - openblas=0.3.17=pthreads_h4748800_1
  - opencv=4.5.0=py39_6
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py39hde0f152_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.0.1=py39he69867a_1
  - pip=21.2.4=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.0=py39hef51801_6
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd8ed1ab_0
  - pywavelets=1.2.0=py39hce5d2b2_1
  - pyyaml=6.0=py39h3811e60_3
  - pyzmq=19.0.2=py39hb69f2a1_2
  - qt=5.12.9=hda022c4_4
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=pyhd8ed1ab_0
  - scikit-image=0.19.2=py39hde0f152_0
  - scikit-learn=0.23.2=py39hf3c863f_3
  - scipy=1.8.0=py39hee8e79c_1
  - setuptools=58.0.4=py39h06a4308_0
  - shapely=1.8.0=py39ha65c37e_5
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.38.0=hc218d9a_0
  - svt-av1=0.9.1=h27087fc_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2022.2.9=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - torchfile=0.1.0=py_0
  - tornado=6.1=py39h3811e60_2
  - tzdata=2021e=hda174b7_0
  - unicodedata2=14.0.0=py39h3811e60_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - visdom=0.1.8.9=0
  - websocket-client=1.3.3=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=0.5.5=h9c3ff4c_8
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - cachetools==5.2.0
    - docker-pycreds==0.4.0
    - frozenlist==1.3.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.48.1
    - importlib-metadata==4.12.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - multidict==6.0.2
    - oauthlib==3.2.1
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pylibtiff==0.4.4.dev0+f14858b
    - pytorch-lightning==1.7.5
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - sentry-sdk==1.9.0
    - setproctitle==1.3.0
    - shortuuid==1.0.9
    - smmap==5.0.0
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - torch==1.9.1
    - torchmetrics==0.9.3
    - torchvision==0.10.1
    - tqdm==4.64.1
    - typing-extensions==4.1.1
    - wandb==0.12.21
    - werkzeug==2.2.2
    - yarl==1.8.1
    - zipp==3.8.1
prefix: /home/sasank/miniconda3/envs/sasank-jtml-env
