name: base
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - brotlipy=0.7.0=py310h5764c6d_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.14=ha878542_0
  - certifi=2022.9.14=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - conda=4.14.0=py310hff52083_0
  - conda-package-handling=1.9.0=py310h5764c6d_0
  - cryptography=37.0.4=py310h597c629_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libarchive=3.5.2=hb890918_3
  - libcurl=7.83.1=h7bff187_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libmamba=0.25.0=hd8a31e3_2
  - libmambapy=0.25.0=py310hab0e683_2
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libsolv=0.7.22=h6239696_0
  - libsqlite=3.39.3=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libuuid=2.32.1=h7f98852_1000
  - libxml2=2.9.14=h22db469_4
  - libzlib=1.2.12=h166bdaf_3
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - mamba=0.25.0=py310hf87f941_2
  - ncurses=6.3=h27087fc_1
  - openssl=1.1.1q=h166bdaf_0
  - pip=22.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.3=py310h5764c6d_1010
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.6=h582c2e5_0_cpython
  - python_abi=3.10=2_cp310
  - readline=8.1.2=h0f457ee_0
  - reproc=14.2.3=h7f98852_0
  - reproc-cpp=14.2.3=h9c3ff4c_0
  - requests=2.28.1=pyhd8ed1ab_1
  - ruamel_yaml=0.15.80=py310h5764c6d_1007
  - setuptools=65.3.0=pyhd8ed1ab_1
  - tk=8.6.12=h27826a3_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - tzdata=2022c=h191b570_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.7.0=h27087fc_1
  - zstd=1.5.2=h6239696_4
  - pip:
    - albumentations==1.3.0
    - click==8.1.3
    - docker-pycreds==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - imageio==2.22.0
    - joblib==1.2.0
    - markupsafe==2.1.1
    - networkx==2.8.6
    - numpy==1.23.3
    - opencv-python-headless==4.6.0.66
    - pathtools==0.1.2
    - pillow==9.2.0
    - promise==2.3
    - psutil==5.9.2
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - sentry-sdk==1.9.8
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - six==1.16.0
    - smmap==5.0.0
    - threadpoolctl==3.1.0
    - tifffile==2022.8.12
    - torchvision==0.13.1
    - typing-extensions==4.3.0
    - wandb==0.13.3
prefix: /blue/banks/sasank.desaraju/Sasank_JTML_seg/conda_envs/envs/sasank-jtml-env
