wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.7
    start_time: 1663356616
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      - 23
      4: 3.9.7
      5: 0.12.21
      8:
      - 5
